config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  
  devise_for :users

  get 'user_root' => redirect('/users')

  get 'matches/join/:id' => 'matches#join', as: 'join_team'

  post 'matches/:id/score' => 'matches#score', as: 'match_score'
  post 'matches/:id/rivals' => 'matches#handicap_rivals', as: 'match_rivals'
  
  patch 'users/:user_id/matches/:id' => 'matches#update'
  patch 'matches/:id/score' => 'matches#score'

  get 'users/rankings' => 'users#rankings'
  
  resources :matches, only: [:index, :show, :edit, :update] do
    resources :teams, only: [:index, :show]
  end
  
  resources :users, only: [:index, :show] do
    resources :matches, only: [:index, :show, :new, :create, :edit, :destroy]  do
      resources :teams, only: [:index, :new, :show, :create]
    end
  end

  resources :matches, only: [:index, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  

end

app/views/partials/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>

app/views/partials/_navigation.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container2">
  
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar">H</span>
          <span class="icon-bar">S</span>
          <span class="icon-bar">D</span>
        </button>
        <%= link_to 'PADDLEFY', root_path, class: 'navbar-brand'%>
      </div>
        
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav horizontal">
          <li>
            <%= link_to matches_path do %>
              <i class="material-icons be-menu-icon">today</i> MATCHES
            <% end %>
          </li>

          <li>
            <%= link_to users_path do %>
              <i class="material-icons be-menu-icon">contacts</i> PLAYERS
            <% end %>
          </li>

          <% if user_signed_in? %>
            <li class="col-md">
              <%= link_to user_path(current_user.id) do %>
                <i class="material-icons be-menu-icon">face</i> <%= current_user.name %>
              <% end %>
            </li>
            <li class="col-md">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="material-icons be-menu-icon">power_settings_new</i> Sign Out
              <% end %>
            </li>

          <% else %>
            <li class="col-md">
              <%= link_to new_user_session_path do %>
                <i class="material-icons be-menu-icon">power_settings_new</i> Sign In
              <% end %>
            </li>
            <li class="col-md">
              <%= link_to new_user_registration_path do %>
                 <i class="material-icons be-menu-icon">account_circle</i> Sign Up
              <% end %>
            </li>
            <% end %>  
        </ul>
      </div>
  
    </div>
    
  </nav>