config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  
  devise_for :users

  get 'user_root' => redirect('/users')

  get 'matches/join/:id' => 'matches#join', as: 'join_team'

  post 'matches/:id/score' => 'matches#score', as: 'match_score'
  post 'matches/:id/rivals' => 'matches#handicap_rivals', as: 'match_rivals'
  
  patch 'users/:user_id/matches/:id' => 'matches#update'
  patch 'matches/:id/score' => 'matches#score'

  get 'users/rankings' => 'users#rankings'
  
  resources :matches, only: [:index, :show, :edit, :update] do
    resources :teams, only: [:index, :show]
  end
  
  resources :users, only: [:index, :show] do
    resources :matches, only: [:index, :show, :new, :create, :edit, :destroy]  do
      resources :teams, only: [:index, :new, :show, :create]
    end
  end

  resources :matches, only: [:index, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :matches, foreign_key: "creator_id"
  has_and_belongs_to_many :teams
  has_and_belongs_to_many :matches
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", minithumb: "50x50>" }, default_url: "/images/avatar/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_many :comments

  validates :name, length: {maximum: 30}
  validates :name, format: {with: /\A[a-zA-ZÑñ0-9]+\Z/} #Ver rubular.com
  validates :name, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(name: :asc)
  end


  def show
    @user = User.find(params[:id])
    if current_user
      @user.teams.each do |tm|
        # @user_matches = Match.where("(local_team_id = #{tm.id} OR visit_team_id = #{tm.id}) AND creator_id = #{current_user.id}")
        # @user_matches = Match.where("creator_id = #{current_user.id}").order(date: :asc)
         @user_matches = Match.order(date: :asc)
      end
    end
  end

  def rankings
    @users_ntrp = User.all.order(ntrp: :desc).limit(5)
    @users_recents = User.all.order(created_at: :desc).limit(5)
  end

  # User.group(:ntrp).count
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_handicap_modal.html.erb
<div class="modal fade" id="handicapModal" tabindex="-1" role="dialog" aria-labelledby="handicapModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="handicapModalLabel">HANDICAP VOTING</h4>
      </div>

      <div class="modal-handicap-body">
        
      </div>

      <div class="modal-footer">
        <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
        <button id="submitHandicap" type="submit" class='btn btn-primary' data-judge="<%= current_user.id%>">Save changes</button>
      </div>
    </div>
  </div>
</div>





<div class="modal fade" id="lost" tabindex="-1" role="dialog" aria-labelledby="lostLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="lostLabel">HANDICAP VOTING</h4>
      </div>

      <div class="modal-body">
       <div class="panel-body">
        <span>
          Adaptación al padel del sistema de puntuación que utilizan en USA para catalogar a los tenistas. Ellos lo llaman NTRP (National Tennis Rating Program), programa nacional de evaluación tenística. La puntuación va del 1.0 al 7.0 y estas son las instrucciones para evaluarse...
        </span>
      </div>
      </div>

      <div class="modal-footer">
        <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
        <button id="submitHandicap" type="submit" class='btn btn-primary'>Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_score_modal.html.erb
<div class='score-container'>
  <div class="modal fade" id="scoreModal" tabindex="-1" role="dialog" aria-labelledby="scoreModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
      
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="scoreModalLabel">MATCH SCORE</h4>
        </div>

        <div class="modal-body">
          <img src='/assets/score.jpg' alt='score' id='score-img'>
          <div class='score-sets'> 
            <div class='set'>
              <label>SET 1</label>
              <input type='number' name='games1-local' min='0' max='7' pattern='[0-7]{1}'>
              <input type='number' name='games1-visit' min='0' max='7' pattern='[0-7]{1}'>
            </div>
            <div class='set'>
              <label>SET 2</label>
              <input type='number' name='games2-local' min='0' max='7' pattern='[0-7]{1}'>
              <input type='number' name='games2-visit' min='0' max='7' pattern='[0-7]{1}'>
            </div>
            <div class='set'>
              <label>SET 3</label>
              <input type='number' name='games3-local' min='0' max='7' pattern='[0-7]{1}'>
              <input type='number' name='games3-visit' min='0' max='7' pattern='[0-7]{1}'>
            </div>
            <div class='set'>
              <label>SET 4</label>
              <input type='number' name='games4-local' min='0' max='7' pattern='[0-7]{1}'>
              <input type='number' name='games4-visit' min='0' max='7' pattern='[0-7]{1}'>
            </div>
            <div class='set'>
              <label>SET 5</label>
              <input type='number' name='games5-local' min='0' max='7' pattern='[0-7]{1}'>
              <input type='number' name='games5-visit' min='0' max='7' pattern='[0-7]{1}'>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
          <button id="submitScore" type="submit" class='btn btn-primary'>Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_matches.html.erb
<span class="title">MY MATCHES 
(Total: <span id="match_total"><%= matches_user_play(current_user,3) %> - </span>
Played: <span id="match_play"><%= matches_user_play(current_user, 0) %> - </span>
Won: <span id="match_win"><%= matches_user_play(current_user,1) %> - </span>
Lost: <span id="match_lose"><%= matches_user_play(current_user, 2) %>)</span>
</span>
<% if @user_matches %>
  <table class="table table-bordered table-hover table-responsive my-matches">
    <thead>
      <tr>
        <th>Wins/Losses</th>
        <th>Date - Time</th>
        <th>Place</th>
        <th>Price</th>
        <th>Rivals</th>
        <th>Rival Votes</th>
        <th>Edit Match</th>
      </tr>
    </thead>
    <tbody>  
    
      <% @user_matches.each do |um| %>
        <% if user_belongs_to_match?(um, current_user) %>
            <% unless build_score(um) != "- - - - - " && build_score(um) != "" %>
              <tr>
                <td>
                  <% if um.creator_id === current_user.id %>
                    <a href="#" class="btn btn-primary btn-score my-score my-button" 
                    data-toggle="modal" data-target="#scoreModal" data-match="<%= um.id %>">SET SCORE</a>
                  <% else %>
                    <span>NO RESULT YET</span>
                  <% end %>
            <% else %>
              <% if user_wins_match(um, current_user) %>
                <tr class="success">
                  <td>
                <a href="#" class="btn btn-success my-button" disabled>WIN</a>
              <% elsif user_lose_match(um, current_user) %>
                <tr class="danger">
                  <td>
                    <a href="#" class="btn btn-danger my-button" disabled>LOSE</a>
              <% end %>
            <% end %>
                  </td>
                  <td><%=link_to um.date.strftime('%F') + ' (' + um.date.strftime("%H:%M") + ')', match_path(um.id) %></td>
                  <td><%= um.venue %></td>
                  <td><%= um.price %>€</td>
                  <span id="score<%= um.id %>" style="display:none;"><%= build_score(um) %></span>
                  <td>
                    <% um.rivals(current_user).each do |riv| %>
                      <%= image_tag riv.avatar.url(:minithumb), class: 'rivals profile-avatar-index', title: riv.name ,
                       'data-rival-name': riv.name, 'data-rival': riv.id, 'data-player-match': um.id, 'vrival': voted_rival?(um, current_user, riv) %>
                    <% end %>      
                  </td>
                  <td>
                    <a href="#" class="btn btn-info btn-score my-handicap my-button"
                    data-toggle="modal" data-target="#handicapModal" data-match="<%= um.id %>"><i class="material-icons">trending_up</i> RIVAL VOTES</a>
                  </td>
                  <td>
                    <% if um.creator_id === current_user.id %>
                      <a href="<%= edit_user_match_path(current_user, um.id) %>" class="btn btn-success my-button">EDIT</a>
                    <% else %>
                      <span><i class="material-icons be-icon">https</i> NOT OWNER</span>
                    <% end %>
                  </td>
                </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <h5>No matches created yet...</h5>
  <% end %>


  <%= render 'score_modal' %>
  <%= render 'handicap_modal' %>

app/views/users/_user_statistics.html.erb
<span class="title">STATISTICS</span>
<div id="chart"></div>

app/views/users/index.html.erb
<a href="<%= users_rankings_path%>" class="btn btn-success" style="margin: 20px;"><i class="material-icons be-icon">sort</i> RANKINGS</a>

<div class="row">
  <% @users.each do |usr| %>
    <div class="col-sm-6 col-md-2" style="top:20px;">
      <div class="thumbnail">
        <a href="<%= user_path(usr.id) %>"><%= image_tag usr.avatar.url(:thumb), class: 'profile-avatar-index' %></a>
        <div class="caption user-index">
          <h3><%= usr.name %></h3>
          
          <span>NTRP:</span>
          <div class="progress progress-striped">
            <div class="progress-bar progress-bar-warning" style="width: <%= (usr.ntrp*100/6) %>%"><%= usr.ntrp %></div>
          </div>
          <p><a href="<%= user_path(usr.id) %>" class="btn btn-primary" role="button">VIEW PROFILE</a></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/rankings.html.erb
<h1>RANKINGS</h1>

<div class="container">
  <div class="row">

    

    <div class="col-md-6">
    <span class="rankins-title">BEST NTRP</span>
    <% @users_ntrp.each do |usr| %>
      
        <div class="thumbnail">
          
          <a href="<%= user_path(usr.id) %>"><%= image_tag usr.avatar.url(:thumb), class: 'profile-avatar-index' %></a>
          <div class="caption user-index">
            <h3><%= usr.name %></h3>
            
            <span>NTRP:</span>
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-warning" style="width: <%= (usr.ntrp*100/6) %>%"><%= usr.ntrp %></div>
            </div>
            <p><a href="<%= user_path(usr.id) %>" class="btn btn-primary" role="button">VIEW PROFILE</a></p>
          </div>
        </div>


      
    <% end %>
    </div>




    <div class="col-md-6">
    <span class="rankins-title">MOST RECENTS</span>
    <% @users_recents.each do |usr| %>

      <div class="thumbnail">
        <!-- <img src="/assets/user.png" alt="user" class="logo"> -->
        <a href="<%= user_path(usr.id) %>"><%= image_tag usr.avatar.url(:thumb), class: 'profile-avatar-index' %></a>
        <div class="caption user-index">
          <h3><%= usr.name %></h3>
          
          <span>NTRP:</span>
          <div class="progress progress-striped">
            <div class="progress-bar progress-bar-warning" style="width: <%= (usr.ntrp*100/6) %>%"><%= usr.ntrp %></div>
          </div>
          <p><a href="<%= user_path(usr.id) %>" class="btn btn-primary" role="button">VIEW PROFILE</a></p>
        </div>
      </div>

    <% end %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>USER PROFILE</h1>
  </div>
</div>

<div class="row profile-container center-xs">
  <div class="col-xs-3">
    <%= image_tag @user.avatar.url(:medium), class: 'profile-avatar-index' %>
  </div>

  <div class="col-xs-6 profile">

    <p class="sporteur-form-control">Name: <%= @user.name %></p>
    <p class="sporteur-form-control">Height: <%= @user.height %></p>
    <p class="sporteur-form-control">Weight: <%= @user.weight %></p>
    <p class="sporteur-form-control">Hand-Orientation: <%= @user.hand_orientation %></p>
    <p class="sporteur-form-control">NTRP (National Tennis Rating Program): <%= @user.ntrp %></p>
    <% if current_user %>
      <% if current_user==@user %>      
        <a href="<%= new_user_match_path(current_user.id) %>" class="btn btn-success"
         data-hook="create-match">CREATE MATCH</a>
        <a href="<%= edit_user_registration_path %>" class="btn btn-success">EDIT PROFILE</a>
      <% end %>
    <% end %>
  </div>
  
  <div class="col-xs-3">
    <div id="chart"></div>
    </div>
</div>




<% if current_user===@user %>
    <div class="row profile-container">
      <div class="col-xs-12 profile">
        <%= render 'user_matches' %>
      </div>
    </div>
    <div class="row profile-container center-xs">
      <div class="col-xs-10 profile">
        <%= render 'user_statistics' %>
      </div>
    </div>
<% end %>