config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  
  devise_for :users

  get 'user_root' => redirect('/users')

  get 'matches/join/:id' => 'matches#join', as: 'join_team'

  post 'matches/:id/score' => 'matches#score', as: 'match_score'
  post 'matches/:id/rivals' => 'matches#handicap_rivals', as: 'match_rivals'
  
  patch 'users/:user_id/matches/:id' => 'matches#update'
  patch 'matches/:id/score' => 'matches#score'

  get 'users/rankings' => 'users#rankings'
  
  resources :matches, only: [:index, :show, :edit, :update] do
    resources :teams, only: [:index, :show]
  end
  
  resources :users, only: [:index, :show] do
    resources :matches, only: [:index, :show, :new, :create, :edit, :destroy]  do
      resources :teams, only: [:index, :new, :show, :create]
    end
  end

  resources :matches, only: [:index, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :local, class_name: 'Team', foreign_key: 'local_team_id'
  belongs_to :visit, class_name: 'Team', foreign_key: 'visit_team_id'
  belongs_to :creator, class_name: 'User'
  has_and_belongs_to_many :users
  has_many :points
  has_many :handicaps
  has_many :comments

  validates :date, presence: true
  validates :places, numericality: {only_integer: true}
  
  before_save :default_values


  def default_values
    self.places ||= 4
  end


  def create
     @user = User.find(current_user.id)
     @team = @user.matches.new(team_params)
     if @team.save
       @user.teams << @team
       redirect_to action: 'index', user_id: @user.id 
     else
     render 'new'
     end
  end

  def rivals(user)
    local.users.include?(user) ? visit.users : local.users
  end


  private
  def team_params
    params.require(:match).permit(:name,:tshirtcolor,:address)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  require 'will_paginate'
  require 'will_paginate/array'
  before_action :create_teams, only: [:create]

  def index
    if params[:user_id]
      @matches = Match.where(creator_id: params[:user_id]).order(date: :asc)
    else
      @matches = Match.all.where('date > ?', DateTime.now).order(date: :asc).paginate(page: params[:page], per_page: 3)
    end
  end


  def show
    @match = Match.find_by(id: params[:id])
    @team_local = Team.find_by(id: @match.local_team_id)
    @team_visit = Team.find_by(id: @match.visit_team_id)

    @comments_in_bbdd = @match.comments
    @comment = Comment.new
  end


  def new
    @match = Match.new
  end


  def create
   @match = Match.new(match_params)
   @match.local_team_id = @local_team.id
   @match.visit_team_id = @visit_team.id
   @match.creator_id = current_user.id
   @match.places_busy = 1
   
   if @match.save
     redirect_to matches_path, notice: 'Match was successfully created.' 
   else
     render 'new'
   end
  end

  def edit
    @user = User.find(params[:user_id])
    @match = Match.find(params[:id])
  end


  def update
    @match=Match.find(params[:id])
    if @match.update_attributes match_params
      redirect_to action: :index
    else
      render 'edit'
    end
  end


  def join
    @user = User.find(current_user.id)
    team = Team.find_by(id: params[:id])
    mat = Match.where("(local_team_id = #{team.id} OR visit_team_id = #{team.id})")

    if @user.teams << team
      mat.first.update_attribute(:places_busy, mat.first.places_busy+1)
      # redirect_to matches_path, notice: 'Youre in!.' 
      redirect_to :back
    end
    
  end

  def score
    @match = Match.find(params[:id])

    unless Point.find_by(match_id: params[:id])
      for i in 1..5
        points = Point.new
        points.match_id = @match.id
        points.order = i
        points.local_points = params["game#{i}-local"]
        points.visit_points = params["game#{i}-visit"]
        points.save
      end
    else
      for i in 1..5
        p = Point.where(match_id: params[:id], order: i)
        p[0].update_attribute(:local_points, params["game#{i}-local"])
        p[0].update_attribute(:visit_points, params["game#{i}-visit"])
      end
    end
    who_wins(params)  
  end


  def handicap_rivals
    for i in 0..1
      if params["rival#{i}_id"] && params["rival#{i}_vote"]!=""
        hand = Handicap.new
        hand.match_id = params['match_id']
        hand.judge = params['judge']
        hand.voted_player = params["rival#{i}_id"]
        hand.vote = params["rival#{i}_vote"]
        hand.save

        player = User.find(params["rival#{i}_id"])
        array = Handicap.where("voted_player = #{params["rival#{i}_id"]}")
        player.ntrp = array.average(:vote).to_f.round(2)
        player.save
      end
    end
    redirect_to :back
  end


  def destroy

    mat = Match.find(params[:id])
    user = User.find(params[:user_id])
    team = which_team_belongs_user?(mat, user)
    team.users.delete(user)
  
    mat.update_attribute(:places_busy, mat.places_busy-1)
    redirect_to :back
  end



  private
  def match_params
    params.require(:match).permit(:date, :score, :venue, :price, :places, :lat, :lng)
  end

  def create_teams
    @user = User.find(current_user.id)
    @local_team = @user.teams.create
    @visit_team = Team.create
  end


  def who_wins(params)
    win_lose = 0

    for i in 1..5
      win_lose += params["game#{i}-local"]<=>params["game#{i}-visit"]
    end
    
    m = Match.find(params[:id])
    if win_lose>0
      m.winner = m.local_team_id
      m.loser = m.visit_team_id
    else
      m.winner = m.visit_team_id
      m.loser = m.local_team_id
    end
    m.save
  end


  def which_team_belongs_user?(match, user)
    if match.local.users.exists?(user)
      return match.local
    elsif match.visit.users.exists?(user)
      return match.visit
    else
      return 0
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper

  def user_belongs_to_match?(match, user)
    match.visit.users.exists?(id:current_user.id) || 
    match.local.users.exists?(id:current_user.id)
  end

  def team_belongs_to_match?(match, team)
    match.visit.exists?(id:team.id) || 
    match.local.exists?(id:team.id)
  end

  # def rival_team(match, user)
  #   binding.pry
  #   match.not.teams
  # end

  def user_wins_match(match, user)
    if match.winner
      Team.find(match.winner).users.exists?(user)
    end
  end

  def user_lose_match(match, user)
    if match.loser
      Team.find(match.loser).users.exists?(user)
    end
  end

  def build_score(match)
    points = match.points
    score = ""
    points.each do |p|     
      score << "#{p.local_points}-#{p.visit_points} "
    end
    return score
  end

  def voted_rival?(match, judger, rival)
    Handicap.where(match_id: match, judge: judger, voted_player: rival).exists?
  end


  def matches_user_play(user, type)
    # 0 = total matches played
    # 1 = matches wins
    # 2 = matches lose
    # 3 = total matches
    locals = 0
    visits = 0
    user.teams.each do |t|
      case type
      when 0    
        locals = locals + Match.where("(local_team_id =#{t.id} OR visit_team_id = #{t.id}) 
          AND winner IS NOT NULL AND loser IS NOT NULL").count.to_i
        # visits = visits + Match.where(visit_team_id: t.id).count.to_i
      when 1
        locals = locals + Match.where(winner: t.id).count.to_i
      when 2
        locals = locals + Match.where(loser: t.id).count.to_i
      when 3
        locals = locals + Match.where("(local_team_id =#{t.id} OR visit_team_id = #{t.id})").count.to_i
      end
    end
    total = locals + visits
  end

end

app/views/matches/_match_players.html.erb
  
  <% for i in 0..(@match.places/2)-1 %>
    <% if team.users[i]!=nil %>
      <% if team.users[i]=== current_user %>
        <%= link_to (image_tag team.users[i].avatar.url(:thumb), class: type_user, title: team.users[i].name), user_match_path(current_user,@match), method: :delete, data:{confirm: 'Delete from the match, Are you sure?'} %>
      <% else %>
        <%= image_tag team.users[i].avatar.url(:thumb), class: type_user, title: team.users[i].name %>
      <% end %>
    <% elsif user_signed_in? && !user_belongs_to_match?(@match, current_user) %>
      <a href="<%= join_team_path(team.id) %>" class="btn <%= type %>" data-team="<%= team.id %>">PLAYER</a>
    <% end %>
  <% end %>

app/views/matches/edit.html.erb
<div class="row">
  <div class="col-xs match">
    <div id="map"></div>
  </div>


  <div class="col-xs match new_map edit_map">
    <h3>EDIT MATCH</h3>
    <%= form_for [@user, @match] do |f|%>
      <%= f.label :date %>
      <%= f.datetime_local_field :date, class: 'sporteur-form-control', min: Time.now.to_date  %>
      <br>
      <%= f.label :venue %>
      <%= f.text_field :venue, class: 'sporteur-form-control venue',id: 'venue' %>
      <%= f.text_field :lat, class: 'sporteur-form-control hidden lat', id:'lat_form' %>
      <%= f.text_field :lng, class: 'sporteur-form-control hidden lng', id:'lng_form' %>
      <br>
      <%= f.label :score %>
      <%= f.text_field :score, class: 'sporteur-form-control', value: build_score(@match) %>
      <br>
      <%= f.label :price %>
      <%= f.number_field :price, :class => 'text_field sporteur-form-control', :step => 'any' %>
      <br>
      <%= f.label :places %>
      <%= f.number_field :places, class: 'sporteur-form-control', value: 4 %>
      <br>
      <%= f.submit 'Save', class: 'btn btn-success' %>
    <%end%>
    </div>
</div>

app/views/matches/index.html.erb
<div class="row">

  <div class="col-xs match">
    <div id="map"></div>
  </div>

  <div class="col-xs match show_map" style="top:20px;">
    <h2>MATCHES SCHEDULE</h2>
    <%= will_paginate @matches, :style => 'color:blue' %>
    <% if @matches.length != 0 %>
      <% @matches.each do |mat| %>
        <div class="thumbnail">
          <div class="caption">
            <p class="venue">
              <h5><i class="material-icons be-icon">alarm_on</i> <%= mat.date!=nil ? mat.date.strftime("%A") + " - " + mat.date.strftime('%v') + ' (' + mat.date.strftime("%H:%M") + ')' : mat.date %></h5>
              <div><i class="material-icons be-icon">room</i> <%= mat.venue %></div>
              <div style="margin: 10px 0 0 0;"><a href="<%= match_path(mat.id) %>" class="btn btn-primary" role="button">DETAILS</a> Free places: <%= mat.places - mat.places_busy %></div>
            </p>
            <p class="sporteur-form-control lat hidden"><%= mat.lat %></p>
            <p class="sporteur-form-control lng hidden"><%= mat.lng %></p>
          </div>
        </div>
      <% end %>
      <%= will_paginate @matches, :style => 'color:blue' %>
    <% else %>
      <h4>There is no matches for now... try later</h4>
    <% end %>
  </div>
</div>

app/views/matches/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>NEW MATCH</h1>
  </div>
</div>

<%@match.errors.full_messages.each do |message|%>
  <div class="">
    *<%= message%>
  </div>
<%end%>

<div class="row new_map">
  <div class="col-xs match">
    <!-- <img src="http://clubparayas.es/wp-content/uploads/2013/11/pista-padel-raquetas-2.jpg">        -->

    <%= form_for [current_user, @match] do |f|%>
      <%= f.label :date %>
      <%= f.datetime_local_field :date, class: 'sporteur-form-control', min: Time.now.to_date %>
      <br>
      <%= f.label :venue %>
      <%= f.text_field :venue, placeholder: 'Enter a location', class: 'sporteur-form-control', id:'venue' %>
      <%= f.text_field :lat, class: 'sporteur-form-control hidden', id:'lat_form' %>
      <%= f.text_field :lng, class: 'sporteur-form-control hidden', id:'lng_form' %>
      <br>
      <%= f.label :price %>
      <%= f.number_field :price, placeholder: 'Total amount (in Euros) for play the match', :class => 'text_field sporteur-form-control', :step => 'any' %>
      <br>
      <%= f.label :places %>
      <%= f.number_field :places, class: 'sporteur-form-control', value: 4 %>
      <br>
      <%= f.submit 'Save', class: 'btn btn-success' %>
    <%end%>
  </div>
  <div class="col-xs match">
    <div id="map"></div>
  </div>
</div>

app/views/matches/show.html.erb
<div class="row">
  
  <div class="col-xs match">
    <div id="map"></div>
  </div>

  <div class="col-xs match show_map">
    <h3>MATCH DETAILS ...</h3>
    <% if @match.date < DateTime.now %>
      <p class="sporteur-form-control">Score: <%= build_score(@match) %></p>
    <% end %>
    <p class="sporteur-form-control">Date: <%=  @match.date!=nil ?  @match.date.strftime("%A") +" - " +  @match.date.strftime('%v') + ' (' +  @match.date.strftime("%H:%M") + ')' :  @match.date %></p>
    <p class="sporteur-form-control venue">Venue: <%= @match.venue %></p>
    <p class="sporteur-form-control">Price: <%= @match.price %> €</p>
    <p class="sporteur-form-control">Places: <%= @match.places %></p>
    <p class="sporteur-form-control">Free Places: <%= @match.places - @match.places_busy %></p>
    <p class="sporteur-form-control lat hidden"><%= @match.lat %></p>
    <p class="sporteur-form-control lng hidden"><%= @match.lng %></p>
    
    
    <%= render 'match_players', team: @team_local, type_user: 'profile-avatar-index_local', type: 'btn-primary' %>
    <%= render 'match_players', team: @team_visit, type_user: 'profile-avatar-index_visit', type: 'btn-success' %>

      <div>
        <%= form_for [@match, @comment] do |f|%>
          <%= f.label 'Comments:'%>
          <%= f.text_area :message, placeholder: 'Write a comment', class:'sporteur-form-control'%>
          <%= f.submit 'Send Comment'%>
        <%end%>
          
        <p>Comments:</p>
          <ul class="nav">
            <%@comments_in_bbdd.each do |comm|%>
            <li>
              <%= image_tag comm.user.avatar.url(:minithumb), class: 'rivals profile-avatar-index', title: comm.user.name %>: <%= comm.message %>
            </li>
            <%end%>
          </ul>
      </div>
  </div>
</div>
</div>